### ISSUE TITLE
Exception in thread "main" org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.niket.ITodo' available

### ISSUE THREAD

**Issue by niketsharmagit** [vogellacompany/codeexamples-javaweb#1]
http://www.vogella.com/tutorials/Spring/article.html#exercise_spring_di_bean I am following this documentation. at point 5.2 when I am running the application I am getting NoSuchBeanDefinitionException. 
Exception in thread "main" org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.niket.ITodo' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:346)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:333)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1107)
	at com.niket.Application.main(Application.java:11)

Also methods in Todo.java hashcode(), toString() and equals(Object obj) has @override annotation but these methods are not available in Interface ITodo.java

**Comment by jonashungershausen** [comment]
Hi,
thanks for reporting an issue.

1. Did you make sure your `Todo` class extends the `ITodo` interface?
2. Does the `Todo` class have the `@Component` annotation?

> Also methods in Todo.java hashcode(), toString() and equals(Object obj) has @override annotation but these methods are not available in Interface ITodo.java

`hashCode`, `toString` and `equals` are standard methods that any class in java has. Thus they should be available to `@Override`, regardless of wether the parent interface has it or not.
Read more here: http://www.vogella.com/tutorials/JavaIntroduction/article.html#javadef_objectsuperclass

You are essentially overriding the methods from the `Object` superclass (that every class in Java has) and not from the interface.

**Comment by niketsharmagit** [comment]
Thanks,
It has been fixed, I have given wrong package name in @ComponentScan.

@Override is working for toString() and equals method but for hashCode IDE is giving : The method hashcode() of type Todo must override or implement a supertype method. Therefore I removed it. 

Also can you provide me any link where I can learn annotations in detail because I am a bit confused about @Autowired.

**Comment by jonashungershausen** [comment]
Glad, you could fix your problem.

> @override is working for toString() and equals method but for hashCode IDE is giving : The method hashcode() of type Todo must override or implement a supertype method. Therefore I removed it.

The correct spelling for that method is `hashCode` with a capital `C`.

>Also can you provide me any link where I can learn annotations in detail because I am a bit confused about @Autowired.

Generally [this](http://www.vogella.com/tutorials/JavaIntroduction/article.html#javaannotations) gives a good overview about what `@Annotations` are. 

`@Autowired` is described here: [SpringDependencyInjection](http://www.vogella.com/tutorials/SpringDependencyInjection/article.html#usageannotations)

**Comment by niketsharmagit** [comment]
Thanks. I missed it. I have one more issue. 

com.vogella.spring.jpa project I have imported but as mentioned in tutorial @Data`annotation is used to generate getters and setters for the `Todo entity. But in my project it is not generating getters and setters. What should I do?

**Comment by jonashungershausen** [comment]
> com.vogella.spring.jpa project I have imported but as mentioned in tutorial @DaTa (Data I don't know it is showing T capital ) annotation is used to generate getters and setters for the `Todo entity. But in my project it is not generating getters and setters. What should I do?

You will need to setup lombok for that to work. [Here](http://www.vogella.com/tutorials/Lombok/article.html) is described how to set it up.

> http://www.vogella.com/tutorials/JavaIntroduction/article.html#javaannotations this link is about java annotations I am asking for Spring annotations.

Well, I gave you the description for the `@Autowired` annotation:
>@Autowired is described here: [SpringDependencyInjection](http://www.vogella.com/tutorials/SpringDependencyInjection/article.html#usageannotations)

 There is not really that much more to it.
